### ISSUE TITLE
[bridges] well founded formulation of Gel-eta

### ISSUE THREAD

**Issue by antoinevanmuylder** [antoinevanmuylder/agda#4]
Consider the following context Γ
```agda
(ℓ : Level) (A0 A1 Set ℓ) (R : A0 → A1 → Set ℓ)
(P Q : (@tick x : BI) → Gel A0 A1 R x) (@tick r : BI)
```
When asking whether `P r versus Q r` are equal members of `Gel A0 A1 R r`, the current implementation (compareTerm' in Conversion.hs) does the following.
1. We make sure that r is semifresh in `P r` and `Q r` which is the case in our context ( `r`is semifresh in M if Γ \r, r ⊢ M).
2. if (1) is met, it is sound to capture r in `P` and `Q` and build the abstractions ` λ r'. P r'` and ` λ r'. Q r'`. We call a comparison at endpoints, eg `(λ r'. P r')(bi0) versus (λ r'. Q r')(bi0)`
3. if (2) is met, `ungel ( λ r'. P r')` and `ungel ( λ r'. Q r')` have the same type. We call a comparison between those two terms.

The problem is that the last call to compareTerm' in (3) goes under `ungel` and `λ` and we are back to comparing `P r versus Q r`, which leads to a loop.

@Saizan would you have an idea how to break this circularity? I wonder if you had the same problem for `Glue` and how you solved it. seems related to
https://github.com/antoinevanmuylder/agda/blob/761886835c2a4ee9a0f3194b2a8cb66dd39b7df5/src/full/Agda/TypeChecking/Conversion.hs#L612

**Comment by antoinevanmuylder** [comment]
another possibility would be to directly encode the eta rule: 
`Q r = gel (Q bi0) (Q bi1) ungel(λ r'. Q r')`
instead of the above more or less equivalent formulation

**Comment by Saizan** [comment]
Yeah, you need to do something similar to compareUnglueApp but for ungel.
